#include "mimetypes.h"

#include "hash_table.h"

static ht* mimetypes=NULL;
static int flag=0;

int mimetypes_init(){
	if(flag) return 0;
	mimetypes=ht_create();
	if(!mimetypes) return 1;
	flag=1;
	ht_set(mimetypes , ".js" ,  "text/javascript" );
	ht_set(mimetypes , ".mjs" ,  "text/javascript" );
	ht_set(mimetypes , ".json" ,  "application/json" );
	ht_set(mimetypes , ".webmanifest" ,  "application/manifest+json" );
	ht_set(mimetypes , ".doc" ,  "application/msword" );
	ht_set(mimetypes , ".dot" ,  "application/msword" );
	ht_set(mimetypes , ".wiz" ,  "application/msword" );
	ht_set(mimetypes , ".nq" ,  "application/n-quads" );
	ht_set(mimetypes , ".nt" ,  "application/n-triples" );
	ht_set(mimetypes , ".bin" ,  "application/octet-stream" );
	ht_set(mimetypes , ".a" ,  "application/octet-stream" );
	ht_set(mimetypes , ".dll" ,  "application/octet-stream" );
	ht_set(mimetypes , ".exe" ,  "application/octet-stream" );
	ht_set(mimetypes , ".o" ,  "application/octet-stream" );
	ht_set(mimetypes , ".obj" ,  "application/octet-stream" );
	ht_set(mimetypes , ".so" ,  "application/octet-stream" );
	ht_set(mimetypes , ".oda" ,  "application/oda" );
	ht_set(mimetypes , ".pdf" ,  "application/pdf" );
	ht_set(mimetypes , ".p7c" ,  "application/pkcs7-mime" );
	ht_set(mimetypes , ".ps" ,  "application/postscript" );
	ht_set(mimetypes , ".ai" ,  "application/postscript" );
	ht_set(mimetypes , ".eps" ,  "application/postscript" );
	ht_set(mimetypes , ".trig" ,  "application/trig" );
	ht_set(mimetypes , ".m3u" ,  "application/vnd.apple.mpegurl" );
	ht_set(mimetypes , ".m3u8" ,  "application/vnd.apple.mpegurl" );
	ht_set(mimetypes , ".xls" ,  "application/vnd.ms-excel" );
	ht_set(mimetypes , ".xlb" ,  "application/vnd.ms-excel" );
	ht_set(mimetypes , ".ppt" ,  "application/vnd.ms-powerpoint" );
	ht_set(mimetypes , ".pot" ,  "application/vnd.ms-powerpoint" );
	ht_set(mimetypes , ".ppa" ,  "application/vnd.ms-powerpoint" );
	ht_set(mimetypes , ".pps" ,  "application/vnd.ms-powerpoint" );
	ht_set(mimetypes , ".pwz" ,  "application/vnd.ms-powerpoint" );
	ht_set(mimetypes , ".wasm" ,  "application/wasm" );
	ht_set(mimetypes , ".bcpio" ,  "application/x-bcpio" );
	ht_set(mimetypes , ".cpio" ,  "application/x-cpio" );
	ht_set(mimetypes , ".csh" ,  "application/x-csh" );
	ht_set(mimetypes , ".dvi" ,  "application/x-dvi" );
	ht_set(mimetypes , ".gtar" ,  "application/x-gtar" );
	ht_set(mimetypes , ".hdf" ,  "application/x-hdf" );
	ht_set(mimetypes , ".h5" ,  "application/x-hdf5" );
	ht_set(mimetypes , ".latex" ,  "application/x-latex" );
	ht_set(mimetypes , ".mif" ,  "application/x-mif" );
	ht_set(mimetypes , ".cdf" ,  "application/x-netcdf" );
	ht_set(mimetypes , ".nc" ,  "application/x-netcdf" );
	ht_set(mimetypes , ".p12" ,  "application/x-pkcs12" );
	ht_set(mimetypes , ".pfx" ,  "application/x-pkcs12" );
	ht_set(mimetypes , ".ram" ,  "application/x-pn-realaudio" );
	ht_set(mimetypes , ".pyc" ,  "application/x-python-code" );
	ht_set(mimetypes , ".pyo" ,  "application/x-python-code" );
	ht_set(mimetypes , ".sh" ,  "application/x-sh" );
	ht_set(mimetypes , ".shar" ,  "application/x-shar" );
	ht_set(mimetypes , ".swf" ,  "application/x-shockwave-flash" );
	ht_set(mimetypes , ".sv4cpio" ,  "application/x-sv4cpio" );
	ht_set(mimetypes , ".sv4crc" ,  "application/x-sv4crc" );
	ht_set(mimetypes , ".tar" ,  "application/x-tar" );
	ht_set(mimetypes , ".tcl" ,  "application/x-tcl" );
	ht_set(mimetypes , ".tex" ,  "application/x-tex" );
	ht_set(mimetypes , ".texi" ,  "application/x-texinfo" );
	ht_set(mimetypes , ".texinfo" ,  "application/x-texinfo" );
	ht_set(mimetypes , ".roff" ,  "application/x-troff" );
	ht_set(mimetypes , ".t" ,  "application/x-troff" );
	ht_set(mimetypes , ".tr" ,  "application/x-troff" );
	ht_set(mimetypes , ".man" ,  "application/x-troff-man" );
	ht_set(mimetypes , ".me" ,  "application/x-troff-me" );
	ht_set(mimetypes , ".ms" ,  "application/x-troff-ms" );
	ht_set(mimetypes , ".ustar" ,  "application/x-ustar" );
	ht_set(mimetypes , ".src" ,  "application/x-wais-source" );
	ht_set(mimetypes , ".xsl" ,  "application/xml" );
	ht_set(mimetypes , ".rdf" ,  "application/xml" );
	ht_set(mimetypes , ".wsdl" ,  "application/xml" );
	ht_set(mimetypes , ".xpdl" ,  "application/xml" );
	ht_set(mimetypes , ".zip" ,  "application/zip" );
	ht_set(mimetypes , ".3gp" ,  "audio/3gpp" );
	ht_set(mimetypes , ".3gpp" ,  "audio/3gpp" );
	ht_set(mimetypes , ".3g2" ,  "audio/3gpp2" );
	ht_set(mimetypes , ".3gpp2" ,  "audio/3gpp2" );
	ht_set(mimetypes , ".aac" ,  "audio/aac" );
	ht_set(mimetypes , ".adts" ,  "audio/aac" );
	ht_set(mimetypes , ".loas" ,  "audio/aac" );
	ht_set(mimetypes , ".ass" ,  "audio/aac" );
	ht_set(mimetypes , ".au" ,  "audio/basic" );
	ht_set(mimetypes , ".snd" ,  "audio/basic" );
	ht_set(mimetypes , ".mp3" ,  "audio/mpeg" );
	ht_set(mimetypes , ".mp2" ,  "audio/mpeg" );
	ht_set(mimetypes , ".opus" ,  "audio/opus" );
	ht_set(mimetypes , ".aif" ,  "audio/x-aiff" );
	ht_set(mimetypes , ".aifc" ,  "audio/x-aiff" );
	ht_set(mimetypes , ".aiff" ,  "audio/x-aiff" );
	ht_set(mimetypes , ".ra" ,  "audio/x-pn-realaudio" );
	ht_set(mimetypes , ".wav" ,  "audio/x-wav" );
	ht_set(mimetypes , ".avif" ,  "image/avif" );
	ht_set(mimetypes , ".bmp" ,  "image/bmp" );
	ht_set(mimetypes , ".gif" ,  "image/gif" );
	ht_set(mimetypes , ".ief" ,  "image/ief" );
	ht_set(mimetypes , ".jpg" ,  "image/jpeg" );
	ht_set(mimetypes , ".jpe" ,  "image/jpeg" );
	ht_set(mimetypes , ".jpeg" ,  "image/jpeg" );
	ht_set(mimetypes , ".heic" ,  "image/heic" );
	ht_set(mimetypes , ".heif" ,  "image/heif" );
	ht_set(mimetypes , ".png" ,  "image/png" );
	ht_set(mimetypes , ".svg" ,  "image/svg+xml" );
	ht_set(mimetypes , ".tiff" ,  "image/tiff" );
	ht_set(mimetypes , ".tif" ,  "image/tiff" );
	ht_set(mimetypes , ".ico" ,  "image/vnd.microsoft.icon" );
	ht_set(mimetypes , ".webp" ,  "image/webp" );
	ht_set(mimetypes , ".ras" ,  "image/x-cmu-raster" );
	ht_set(mimetypes , ".pnm" ,  "image/x-portable-anymap" );
	ht_set(mimetypes , ".pbm" ,  "image/x-portable-bitmap" );
	ht_set(mimetypes , ".pgm" ,  "image/x-portable-graymap" );
	ht_set(mimetypes , ".ppm" ,  "image/x-portable-pixmap" );
	ht_set(mimetypes , ".rgb" ,  "image/x-rgb" );
	ht_set(mimetypes , ".xbm" ,  "image/x-xbitmap" );
	ht_set(mimetypes , ".xpm" ,  "image/x-xpixmap" );
	ht_set(mimetypes , ".xwd" ,  "image/x-xwindowdump" );
	ht_set(mimetypes , ".eml" ,  "message/rfc822" );
	ht_set(mimetypes , ".mht" ,  "message/rfc822" );
	ht_set(mimetypes , ".mhtml" ,  "message/rfc822" );
	ht_set(mimetypes , ".nws" ,  "message/rfc822" );
	ht_set(mimetypes , ".css" ,  "text/css" );
	ht_set(mimetypes , ".csv" ,  "text/csv" );
	ht_set(mimetypes , ".html" ,  "text/html" );
	ht_set(mimetypes , ".htm" ,  "text/html" );
	ht_set(mimetypes , ".md" ,  "text/markdown" );
	ht_set(mimetypes , ".markdown" ,  "text/markdown" );
	ht_set(mimetypes , ".n3" ,  "text/n3" );
	ht_set(mimetypes , ".txt" ,  "text/plain" );
	ht_set(mimetypes , ".bat" ,  "text/plain" );
	ht_set(mimetypes , ".c" ,  "text/plain" );
	ht_set(mimetypes , ".h" ,  "text/plain" );
	ht_set(mimetypes , ".ksh" ,  "text/plain" );
	ht_set(mimetypes , ".pl" ,  "text/plain" );
	ht_set(mimetypes , ".srt" ,  "text/plain" );
	ht_set(mimetypes , ".rtx" ,  "text/richtext" );
	ht_set(mimetypes , ".rtf" ,  "text/rtf" );
	ht_set(mimetypes , ".tsv" ,  "text/tab-separated-values" );
	ht_set(mimetypes , ".vtt" ,  "text/vtt" );
	ht_set(mimetypes , ".py" ,  "text/x-python" );
	ht_set(mimetypes , ".rst" ,  "text/x-rst" );
	ht_set(mimetypes , ".etx" ,  "text/x-setext" );
	ht_set(mimetypes , ".sgm" ,  "text/x-sgml" );
	ht_set(mimetypes , ".sgml" ,  "text/x-sgml" );
	ht_set(mimetypes , ".vcf" ,  "text/x-vcard" );
	ht_set(mimetypes , ".xml" ,  "text/xml" );
	ht_set(mimetypes , ".mp4" ,  "video/mp4" );
	ht_set(mimetypes , ".mpeg" ,  "video/mpeg" );
	ht_set(mimetypes , ".m1v" ,  "video/mpeg" );
	ht_set(mimetypes , ".mpa" ,  "video/mpeg" );
	ht_set(mimetypes , ".mpe" ,  "video/mpeg" );
	ht_set(mimetypes , ".mpg" ,  "video/mpeg" );
	ht_set(mimetypes , ".mov" ,  "video/quicktime" );
	ht_set(mimetypes , ".qt" ,  "video/quicktime" );
	ht_set(mimetypes , ".webm" ,  "video/webm" );
	ht_set(mimetypes , ".avi" ,  "video/x-msvideo" );
	ht_set(mimetypes , ".movie" ,  "video/x-sgi-movie" );
	return 0;
}

void mimetypes_quit(){
	if(mimetypes) ht_destory(mimetypes);
}
char* get_mime(char* ext){
	char* dest=ht_get(mimetypes, ext);
	return (dest) ? dest : "application/octet-stream";
}

